#!/bin/bash

clear

red="\033[1;31m"
green="\033[0;32m"
cyan="\033[0;36m"
yellow="\033[0;37m"
f="\033[0m"

invalidOption="${red}>>> PORTA INVÁLIDA!$f";
logo="${yellow}RDY ${red}SOFTWARE ${yellow}{ ${red}} ${cyan}21/05/2022$f";





function listOption(){

running=$(firewall-cmd --state)
zone=$(firewall-cmd --get-default-zone)

echo -e "$logo";
echo -e "${cyan}>>>> FIREWALL MANAGER <<<<$f";
echo -e "${yellow}Firewall status: ${green}$running$f"
echo -e "${yellow}Zone: ${green}$zone$f"
echo -e ""
echo -e "{yellow}[01] Abrir porta$f"
echo -e "{yellow}[02] Bloquear porta$f"
echo -e "{yellow}[03] Listar portas$f"
echo -e ""; 
read -p "Escolha a opção[01-03]: " op


case $op in
1|01) 
openPortStart
;;
2|02)
closePortStart
;;

3|03)
firewall-cmd --zone=public --list-ports
;;

*)
 echo -e "$invalidOption"
   exit
;;

esac

#sudo firewall-cmd --zone=public --list-ports
    
}

#listar portas
# firewall-cmd --zone=public --list-ports

listOption
